//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhongMachTu.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiDinhDungThuoc
    {
        public int ID { get; set; }
        public string MaPK { get; set; }
        public string MaThuoc { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string MaDonVi { get; set; }
        public string MaCachDung { get; set; }
        public string GhiChu { get; set; }
    
        public virtual CachDungThuoc CachDungThuoc { get; set; }
        public virtual DonViThuoc DonViThuoc { get; set; }
        public virtual Thuoc Thuoc { get; set; }
    }
}
