//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhongMachTu.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachKhamBenh
    {
        public int ID { get; set; }
        public string MaDS { get; set; }
        public Nullable<System.DateTime> NgayKham { get; set; }
        public Nullable<int> SoLuong { get; set; }
    }
}
