//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhongMachTu.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int ID { get; set; }
        public string MaHD { get; set; }
        public string MaPK { get; set; }
        public System.DateTime NgayLap { get; set; }
        public int TienKham { get; set; }
        public int TienThuoc { get; set; }
        public int TongTienThanhToan { get; set; }
    
        public virtual PhieuKhamBenh PhieuKhamBenh { get; set; }
    }
}
