//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhongMachTu.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLYPHONGKHAMTUEntities : DbContext
    {
        public QLYPHONGKHAMTUEntities()
            : base("name=QLYPHONGKHAMTUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BenhNhan> BenhNhans { get; set; }
        public virtual DbSet<CachDungThuoc> CachDungThuocs { get; set; }
        public virtual DbSet<ChiDinhDungThuoc> ChiDinhDungThuocs { get; set; }
        public virtual DbSet<ChiTietD> ChiTietDS { get; set; }
        public virtual DbSet<ChiTietThongKeThuoc> ChiTietThongKeThuocs { get; set; }
        public virtual DbSet<DanhSachKhamBenh> DanhSachKhamBenhs { get; set; }
        public virtual DbSet<DonViThuoc> DonViThuocs { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhieuKhamBenh> PhieuKhamBenhs { get; set; }
        public virtual DbSet<QuyDinh> QuyDinhs { get; set; }
        public virtual DbSet<ThongKeThuoc> ThongKeThuocs { get; set; }
        public virtual DbSet<Thuoc> Thuocs { get; set; }
    }
}
